{{- range $key, $config := .Values.global.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $configKey, $configValue := $config.data }}
  {{ $configKey }}: {{ $configValue | quote }}
{{- end }}
---
{{- end }}