{{- range $key, $secret := .Values.global.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $dataKey, $dataValue := $secret.data }}
  {{- $dataKey }}: {{ $dataValue | quote}}
{{- end }}
---
{{- end }}