apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-backend.fullname" . }}
  namespace: {{ $.Release.Namespace | default "default"}}
  labels:
    {{- include "demo-app-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-app-backend.selectorLabels" . | nindent 4 }}
