{{- range $key, $config := .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}
  namespace: {{ $.Release.Namespace | default "default"}}
data:
{{- range $configKey, $configValue := $config.data }}
  {{ $configKey }}: {{ $configValue | quote }}
{{- end }}
---
{{- end }}